[theme]
base="light"
backgroundColor="ghostWhite"
secondaryBackgroundColor="lavender"
textColor="lavender"
primaryColor="skyBlue"

# [theme.sidebar]
# backgroundColor="ghostWhite"
# secondaryBackgroundColor="lavender"
